"""Create profile table

Revision ID: 6ee5474d9a28
Revises: 3517a226028c
Create Date: 2025-06-27 12:54:34.878883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ee5474d9a28"
down_revision: Union[str, Sequence[str], None] = "3517a226028c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("first_name", sa.String(length=40), nullable=True),
        sa.Column("last_name", sa.String(length=40), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.add_column(
        "posts",
        sa.Column("body", sa.Text(), server_default="", nullable=False),
    )
    op.drop_column("posts", "bode")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "bode", sa.TEXT(), server_default=sa.text("('')"), nullable=False
        ),
    )
    op.drop_column("posts", "body")
    op.drop_table("profiles")
    # ### end Alembic commands ###
